import os
import sqlite3
from pathlib import Path

DB_PATH = Path("data/app.db")


def _load_dotenv() -> None:
    env_path = Path(".env")
    if not env_path.exists():
        return

    for raw_line in env_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip())


_load_dotenv()
DATABASE_URL = os.getenv("DATABASE_URL", "")


def is_postgres() -> bool:
    return bool(DATABASE_URL)


def sql(query: str) -> str:
    if is_postgres():
        return query.replace("?", "%s")
    return query


def is_unique_error(exc: Exception) -> bool:
    return isinstance(exc, sqlite3.IntegrityError) or exc.__class__.__name__ == "UniqueViolation"


def get_conn():
    if is_postgres():
        import psycopg
        from psycopg.rows import dict_row

        return psycopg.connect(DATABASE_URL, row_factory=dict_row)

    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def init_db() -> None:
    if is_postgres():
        _init_postgres()
    else:
        _init_sqlite()


def _init_sqlite() -> None:
    with get_conn() as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS orders (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                address TEXT NOT NULL,
                description TEXT,
                price INTEGER,
                status TEXT,
                assignee TEXT,
                paid INTEGER
            )
            """
        )
        columns = {
            row["name"]
            for row in conn.execute("PRAGMA table_info(orders)").fetchall()
        }
        if "latitude" not in columns:
            conn.execute("ALTER TABLE orders ADD COLUMN latitude REAL")
        if "longitude" not in columns:
            conn.execute("ALTER TABLE orders ADD COLUMN longitude REAL")
        if "customer_id" not in columns:
            conn.execute("ALTER TABLE orders ADD COLUMN customer_id INTEGER")
        if "payment_status" not in columns:
            conn.execute("ALTER TABLE orders ADD COLUMN payment_status TEXT DEFAULT 'not_started'")
        if "payment_id" not in columns:
            conn.execute("ALTER TABLE orders ADD COLUMN payment_id TEXT")
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                username TEXT UNIQUE NOT NULL,
                role TEXT NOT NULL,
                password_hash TEXT NOT NULL,
                salt TEXT NOT NULL
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS order_events (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                order_id INTEGER NOT NULL,
                event_type TEXT NOT NULL,
                message TEXT NOT NULL,
                actor TEXT,
                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        )


def _init_postgres() -> None:
    with get_conn() as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS orders (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                address TEXT NOT NULL,
                description TEXT,
                price INTEGER,
                status TEXT,
                assignee TEXT,
                paid INTEGER,
                latitude DOUBLE PRECISION,
                longitude DOUBLE PRECISION,
                customer_id INTEGER,
                payment_status TEXT DEFAULT 'not_started',
                payment_id TEXT
            )
            """
        )
        conn.execute("ALTER TABLE orders ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION")
        conn.execute("ALTER TABLE orders ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION")
        conn.execute("ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_id INTEGER")
        conn.execute("ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_status TEXT DEFAULT 'not_started'")
        conn.execute("ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_id TEXT")
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username TEXT UNIQUE NOT NULL,
                role TEXT NOT NULL,
                password_hash TEXT NOT NULL,
                salt TEXT NOT NULL
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS order_events (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                order_id INTEGER NOT NULL,
                event_type TEXT NOT NULL,
                message TEXT NOT NULL,
                actor TEXT,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
